version: '3'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - selteq_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - selteq_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - selteq_network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=YourStrong@Passw0rd
    networks:
      - selteq_network

  celery:
    build: .
    command: celery -A selteq_task worker -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=YourStrong@Passw0rd
    networks:
      - selteq_network

  celery-beat:
    build: .
    command: celery -A selteq_task beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=YourStrong@Passw0rd
    networks:
      - selteq_network

networks:
  selteq_network:

volumes:
  mssql_data: